/**
 * 适配器统一导出
 */
export type { IPlatformAdapter, PlatformMeta, Article, SyncResult, AuthResult, PlatformCapability } from './interface.js'
export { BaseAdapter } from './base-adapter.js'
export { WeixinAdapter } from './weixin.js'
export { ZhihuAdapter } from './zhihu.js'
export { JuejinAdapter } from './juejin.js'
export { CSDNAdapter } from './csdn.js'
export { WeiboAdapter } from './weibo.js'
export { BilibiliAdapter } from './bilibili.js'
export { BaijiahaoAdapter } from './baijiahao.js'
export { CnblogsAdapter } from './cnblogs.js'
export { DoubanAdapter } from './douban.js'
export { EastmoneyAdapter } from './eastmoney.js'
export { ImoocAdapter } from './imooc.js'
export { OschinaAdapter } from './oschina.js'
export { SegmentfaultAdapter } from './segmentfault.js'
export { SohuAdapter } from './sohu.js'
export { WoshipmAdapter } from './woshipm.js'
export { XueqiuAdapter } from './xueqiu.js'
export { YuqueAdapter } from './yuque.js'
export { Cto51Adapter } from './cto51.js'
export { ToutiaoAdapter } from './toutiao.js'
export { XiaohongshuAdapter } from './xiaohongshu.js'
export { adapterRegistry, initAdapterRegistry, getAdapter, getLoggedInPlatforms, publishToPlatforms } from './registry.js'
